# ----------------------------
# Makefile Options
# ----------------------------

NAME := name
DESCRIPTION := "[Description]"
COMPRESSED := NO
ARCHIVED := NO

HAS_PRINTF := NO

CFLAGS := -Wall -Wextra -Oz
CXXFLAGS := -Wall -Wextra -Oz

# ----------------------------

ifndef CEDEV
$(error CEDEV environment path variable is not set)
endif

include $(CEDEV)/meta/makefile.mk
