NAME := ANSWERS
ICON := icon.png
DESCRIPTION := Playing with Ans
ARCHIVED := YES

HAS_PRINTF := NO

CXXFLAGS := -Wall -Wextra -pedantic -Oz

ifndef CEDEV
$(error CEDEV environment path variable is not set)
endif

include $(CEDEV)/meta/makefile.mk
