# ----------------------------
# Makefile Options
# ----------------------------

NAME := GFXUTILS
DESCRIPTION := "GfxUtils library test"
COMPRESSED := NO
ARCHIVED := YES

HAS_PRINTF := NO

CFLAGS := -Wall -Wextra -Oz -fstrict-enums
CXXFLAGS := -Wall -Wextra -Oz -fstrict-enums

# ----------------------------

ifndef CEDEV
$(error CEDEV environment path variable is not set)
endif

include $(CEDEV)/meta/makefile.mk
