# ----------------------------
# Makefile Options
# ----------------------------

NAME := CHATCHAT
ICON := icon-16.png
DESCRIPTION := "Chat Chat!"
COMPRESSED := NO
ARCHIVED := YES

HAS_PRINTF := YES

CFLAGS := -Wall -Wextra -Oz
CXXFLAGS := -Wall -Wextra -Oz

# ----------------------------

ifndef CEDEV
$(error CEDEV environment path variable is not set)
endif

include $(CEDEV)/meta/makefile.mk
