# ----------------------------
# Makefile Options
# ----------------------------

NAME := MATRIXCE
ICON := icon-16.png
DESCRIPTION := "The famous Matrix on your CE"
COMPRESSED := NO
ARCHIVED := YES

CFLAGS := -Wall -Wextra -Oz
CXXFLAGS := -Wall -Wextra -Oz

# ----------------------------

ifndef CEDEV
$(error CEDEV environment path variable is not set)
endif

include $(CEDEV)/meta/makefile.mk
