NAME := SENDSTR1
DESCRIPTION := "Send Str1 on USB"
ARCHIVED := YES

HAS_PRINTF := NO
CXXFLAGS := -Wall -Wextra -pedantic -Oz

ifndef CEDEV
$(error CEDEV environment path variable is not set)
endif

include $(CEDEV)/meta/makefile.mk