# ----------------------------
# Makefile Options
# ----------------------------

NAME := DNDTOOL
ICON := icon-16.png
DESCRIPTION := "Random D&D Tools"
COMPRESSED := NO
ARCHIVED := YES

HAS_PRINTF := NO

CFLAGS := -Wall -Wextra -Oz
CXXFLAGS := -Wall -Wextra -Oz

# ----------------------------

ifndef CEDEV
$(error CEDEV environment path variable is not set)
endif

include $(CEDEV)/meta/makefile.mk
