NAME := RECVSTR1
DESCRIPTION := "Receive Str1 from USB"
ARCHIVED := YES

HAS_PRINTF := NO
CXXFLAGS := -Wall -Wextra -pedantic -Oz

ifndef CEDEV
$(error CEDEV environment path variable is not set)
endif

include $(CEDEV)/meta/makefile.mk