# ----------------------------
# Makefile Options
# ----------------------------

NAME := FIRST
ICON := icon.png
DESCRIPTION := "FIRST CE C PRGM"
COMPRESSED := NO
ARCHIVED := NO

CFLAGS := -Wall -Wextra -Oz
CXXFLAGS := -Wall -Wextra -Oz

# ----------------------------

ifndef CEDEV
$(error CEDEV environment path variable is not set)
endif

include $(CEDEV)/meta/makefile.mk
