# ----------------------------
# Makefile Options
# ----------------------------

NAME := PONG2
DESCRIPTION := "Description"
COMPRESSED := NO
ARCHIVED := YES

# HAS_PRINTF := NO
HAS_PRINTF := YES

CFLAGS := -Wall -Wextra -Oz
CXXFLAGS := -Wall -Wextra -Oz

# ----------------------------

ifndef CEDEV
$(error CEDEV environment path variable is not set)
endif

include $(CEDEV)/meta/makefile.mk
